bibentry(bibtype = "Article",
         title = "Low-dimensional neural ordinary differential equations accounting for inter-individual variability implemented in Monolix and NONMEM",
         author = c(person(c("Dominic", "S."), "Bräm"),
                    person("Bernhard","Steiert"),
                    person("Marc","Pfister"),
                    person("Britta","Steffens"),
                    person("Gilbert", "Koch")),
         journal = "CPT: Pharmacometrics & Systems Pharmacology",
         year = "2024",
         pages = "1--12",
         url = "https://ascpt.onlinelibrary.wiley.com/doi/abs/10.1002/psp4.13265",
         doi = "10.1002/psp4.13265")

bibentry(bibtype = "Article",
         title = "Low-dimensional neural ODEs and their application in pharmacokinetics",
         author = c(person(c("Dominic", "S."), "Bräm"),
                    person("Uri", "Nahum"),
                    person("Johannes", "Schropp"),
                    person("Marc", "Pfister"),
                    person("Gilbert", "Koch")),
         journal = "Journal of Pharmacokinetics and Pharmacodynamics",
         year = "2024",
         volume = "51",
         pages = "123--140",
         url = "https://doi.org/10.1007/s10928-023-09886-4",
         doi = "10.1007/s10928-023-09886-4")
